# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/hdmi_vga_vp_bin_0_0.xci
# IP: The module: 'hdmi_vga_vp_bin_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/b_lut/b_lut.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_lut || ORIG_REF_NAME==b_lut} -quiet] -quiet

# IP: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/g_lut/g_lut.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==g_lut || ORIG_REF_NAME==g_lut} -quiet] -quiet

# IP: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/r_lut/r_lut.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==r_lut || ORIG_REF_NAME==r_lut} -quiet] -quiet

# XDC: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/b_lut/b_lut_ooc.xdc

# XDC: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/g_lut/g_lut_ooc.xdc

# XDC: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/r_lut/r_lut_ooc.xdc

# IP: C:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/hdmi_vga_vp_bin_0_0.xci
# IP: The module: 'hdmi_vga_vp_bin_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/b_lut/b_lut.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_lut || ORIG_REF_NAME==b_lut} -quiet] -quiet

# IP: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/g_lut/g_lut.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==g_lut || ORIG_REF_NAME==g_lut} -quiet] -quiet

# IP: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/r_lut/r_lut.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==r_lut || ORIG_REF_NAME==r_lut} -quiet] -quiet

# XDC: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/b_lut/b_lut_ooc.xdc

# XDC: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/g_lut/g_lut_ooc.xdc

# XDC: c:/git/SR/lab5/zad85/zad85.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_bin_0_0/ip/r_lut/r_lut_ooc.xdc
