# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/mult_gen_xa/mult_gen_xa.xci
# IP: The module: 'mult_gen_xa' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/mult_gen_xa/mult_gen_xa_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_xa'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/mult_gen_xa/mult_gen_xa.xci
# IP: The module: 'mult_gen_xa' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/mult_gen_xa/mult_gen_xa_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_xa'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
