# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lsriw/sr/RomanMichal/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/b_lut/b_lut.xci
# IP: The module: 'b_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/sr/RomanMichal/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/b_lut/b_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'b_lut'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lsriw/sr/RomanMichal/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/b_lut/b_lut.xci
# IP: The module: 'b_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lsriw/sr/RomanMichal/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/b_lut/b_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'b_lut'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
