# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/c_addsub_y/c_addsub_y.xci
# IP: The module: 'c_addsub_y' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/c_addsub_y/c_addsub_y_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_y'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/c_addsub_y/c_addsub_y.xci
# IP: The module: 'c_addsub_y' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Krasnal/Desktop/Wegrzyn/lab7/vis_circle/vis_circle.srcs/sources_1/ip/c_addsub_y/c_addsub_y_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_y'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
