# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/r_lut/r_lut.xci
# IP: The module: 'r_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/r_lut/r_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_lut'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/git/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/r_lut/r_lut.xci
# IP: The module: 'r_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SR/lab5/vp_bin/vp_bin.srcs/sources_1/ip/r_lut/r_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_lut'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
