# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git/SR/lab12/zad12_1/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/median5x5_0_1/median5x5_0.xci
# IP: The module: 'median5x5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SR/lab12/zad12_1/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/median5x5_0_1/src/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'median5x5_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/git/SR/lab12/zad12_1/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/median5x5_0_1/median5x5_0.xci
# IP: The module: 'median5x5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SR/lab12/zad12_1/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/median5x5_0_1/src/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'median5x5_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
