# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git/SR/lab11/zad11_1/centroid/centroid.srcs/sources_1/ip/acc_m01/acc_m01.xci
# IP: The module: 'acc_m01' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SR/lab11/zad11_1/centroid/centroid.srcs/sources_1/ip/acc_m01/acc_m01_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_m01'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/git/SR/lab11/zad11_1/centroid/centroid.srcs/sources_1/ip/acc_m01/acc_m01.xci
# IP: The module: 'acc_m01' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/SR/lab11/zad11_1/centroid/centroid.srcs/sources_1/ip/acc_m01/acc_m01_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'acc_m01'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
